services:
  - type: web
    name: metadata-extraction-factory
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeployTrigger: commit
    envVars:
      - key: PAGECRYPT_PASSWORD
        sync: false
